version: '3.1'

services:
  db:
    image: postgres
    restart: on-failure
    env_file:
      - .pg.env
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

  app:
    build:
      dockerfile: ./docker/Dockerfile
    ports:
      - 8000:8000

volumes:
  data:
    driver: local
