version: '3.1'

services:
  db:
    image: postgres
    restart: on-failure
    env_file:
      - .pg.env
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
